### ISSUE TITLE
vgg16b on wu has truncated mean at 95%

### ISSUE THREAD

**Issue by echurch** [drinkingkazu/ArchitecturePaperStudy#1]
Please continue training.

![image](https://cloud.githubusercontent.com/assets/8322304/22637470/c65aa212-ebf6-11e6-9817-8b2c4d50c1c6.png)

**Comment by drinkingkazu** [comment]
Current GPU occupation can be found here: https://trello.com/b/amZKeOko/gpu-occupation
where PNNL is just outdated, I think.

I will stop currently running training of plainresnet20b and continue vgg16b training instead.

**Comment by drinkingkazu** [comment]
Training is now resumed @ Michigan site. Updates should be monitored by wu_monitor or paper.html pages.

**Comment by echurch** [comment]
Does this look like signs of overtraining?

![image](https://cloud.githubusercontent.com/assets/8322304/22724842/d45cdf78-ed7d-11e6-8cef-5871ec03dfc2.png)

**Comment by drinkingkazu** [comment]
It does. But there are 2 parts to "overtraining":

0) network performance becomes significantly better for train set compared to test set
1) network performance becomes worse for test set compared to the same test set at earlier epoch

what we care is 1), and I don't see, from accuracy plot, such sign.
Like I explained to you we should be looking at an error rate plot from EpochAnalysis.ipynb instead of these.

**Comment by echurch** [comment]
Update. Perhaps it's converging, despite the train/test divergence by eye.:

![image](https://cloud.githubusercontent.com/assets/8322304/22856350/5ff60370-f044-11e6-8295-484bb2d2a164.png)

**Comment by echurch** [comment]
Kazu, you may stop this run if you'd like. 
![image](https://cloud.githubusercontent.com/assets/8322304/22872235/683ea95a-f16c-11e6-8a8d-2c5fb8d6ebfb.png)

**Comment by drinkingkazu** [comment]
Thanks, replaced w/ resnet 14b!

**Comment by echurch** [comment]
![image](https://cloud.githubusercontent.com/assets/8322304/22918834/22773ede-f241-11e6-9acc-ad7a28ec5c05.png)
